### ISSUE TITLE
Internally making http requests...

### ISSUE THREAD

**Issue by kwierchris** [OpusCapitaBusinessNetwork/useridentity-middleware#7]
Talking to Arne we decided that it is not a good idea to make http requests in useridentity-middleware especially as [this](https://github.com/OpusCapitaBusinessNetwork/useridentity-middleware/blob/master/index.js#L103) is transferring "secret" data over HTTP.

As a conclusion, we will need a local or secret storage for those secrets.

**Comment by sureshvarman-cronj** [comment]
The result is a public key, any one can see this or use this, only to validate the idtoken is from trusted source. So no issue on transferring secrets. but not getting why not http request (internal) in user identity middleware.

**Comment by kwierchris** [comment]
OK, no secret understood.
